# Generated by Django 4.2.3 on 2024-10-05 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_certificate_certifying_institution"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="github",
            new_name="github_url",
        ),
    ]
